server.port=8086

spring.application.name=payment_service

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=payment-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

app.kafka.topic.key-rotation=public-key-rotation
app.kafka.topic.payment-events=payment-events

app.keys.public-key-path=src/main/resources/public_key.pem
app.internal-api-key=27RedTQ4pmJSY/DuSoUULGZJYP+7baxqzGfRGmNwZ3o=

spring.datasource.url=jdbc:postgresql://localhost:5436/payment_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true