server.port=8080

app.keys.private-key-path=src/main/resources/private_key.pem
app.keys.public-key-path=src/main/resources/public_key.pem

spring.application.name=auth_service

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

app.kafka.topic.key-rotation=public-key-rotation
app.jwt.expiration-ms=3600000

app.user-service.base-url=http://localhost:8081